In [2]:
import numpy as np
import scipy as sp
import sympy as smp
import matplotlib.pyplot as plt
from scipy.misc import derivative

In [3]:
t0, t1, t2, t3 = smp.symbols('t0 t1 t2 t3', real=True)
t = [t0,t1,t2,t3]
print(t)

[t0, t1, t2, t3]


In [4]:
g = np.zeros((4,4), dtype = type(smp.sin(t0))) # for S2xS2
print(g)
g[0][0] = 1
g[1][1] = smp.sin(t0)
g[2][2] = 1
g[3][3] = smp.sin(t2)
print(g)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0]
 [0 sin(t0) 0 0]
 [0 0 1 0]
 [0 0 0 sin(t2)]]


In [5]:
g_inv = np.zeros((4,4), dtype = type(smp.sin(t0))) # for S2xS2
g_inv[0][0] = 1
g_inv[1][1] = 1/smp.sin(t0)
g_inv[2][2] = 1
g_inv[3][3] = 1/smp.sin(t2)
print(g_inv)

[[1 0 0 0]
 [0 1/sin(t0) 0 0]
 [0 0 1 0]
 [0 0 0 1/sin(t2)]]


In [6]:
def calc_chrst():
    chrst = np.zeros((4,4,4), dtype = type(smp.sin(t0)))
    for k in range(4):
        for i in range(4): 
            for j in range(4):
                for m in range(4):
                    chrst[k][i][j] += (1/2)*g_inv[k][m]*(smp.diff(g[m][i],t[j]) + smp.diff(g[m][j],t[i]) - smp.diff(g[i][j],t[m]))
    return chrst

print(calc_chrst())

S2_chrst = calc_chrst()
                    
# calculated for S2xS2

[[[0 0 0 0]
  [0 -0.5*cos(t0) 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0.5*cos(t0)/sin(t0) 0 0]
  [0.5*cos(t0)/sin(t0) 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 -0.5*cos(t2)]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0.5*cos(t2)/sin(t2)]
  [0 0 0.5*cos(t2)/sin(t2) 0]]]


In [48]:
g = np.zeros((4,4), dtype = type(smp.sin(t0))) # for H2xH2
g[0][0] = 1/s1
g[1][1] = 1/s1
g[2][2] = 1/s2
g[3][3] = 1/s2
print(g)

[[1/s1 0 0 0]
 [0 1/s1 0 0]
 [0 0 1/s2 0]
 [0 0 0 1/s2]]


In [49]:
g_inv = np.zeros((4,4), dtype = type(smp.sin(t0))) # for H2xH2
g_inv[0][0] = s1
g_inv[1][1] = s1
g_inv[2][2] = s2
g_inv[3][3] = s2
print(g_inv)

[[s1 0 0 0]
 [0 s1 0 0]
 [0 0 s2 0]
 [0 0 0 s2]]


In [50]:
#t = [mu1,s1,mu2,s2] # for H2xH2 might be wrong one
#
#def calc_chrst():
#    chrst = np.zeros((4,4,4), dtype = type(smp.sin(t0)))
#    for k in range(4):
#        for i in range(4): 
#            for j in range(4):
#                for m in range(4):
#                    chrst[k][i][j] += (1/2)*g_inv[k][m]*(smp.diff(g[m][i],t[j]) + smp.diff(g[m][j],t[i]) - smp.diff(g[i][j],t[m]))
#    return chrst
#
#print(calc_chrst())
#
#H2_chrst = calc_chrst()

[[[0 -0.5/s1 0 0]
  [-0.5/s1 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0.5/s1 0 0 0]
  [0 -0.5/s1 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 -0.5/s2]
  [0 0 -0.5/s2 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0.5/s2 0]
  [0 0 0 -0.5/s2]]]


In [77]:
t = [mu1,s1,mu2,s2] # for H2xH2

def calc_chrst():
    chrst = np.zeros((4,4,4), dtype = type(smp.sin(t0)))
    for i in range(4):
        for j in range(4): 
            for k in range(4):
                for m in range(4):
                    chrst[i][j][k] += (1/2)*g_inv[k][m]*(smp.diff(g[m][i],t[j]) + smp.diff(g[m][j],t[i]) - smp.diff(g[i][j],t[m]))
    return chrst

print(calc_chrst())
H2_chrst = calc_chrst()

[[[0 0.5/s1 0 0]
  [-0.5/s1 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[-0.5/s1 0 0 0]
  [0 -0.5/s1 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0.5/s2]
  [0 0 -0.5/s2 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 -0.5/s2 0]
  [0 0 0 -0.5/s2]]]


In [47]:
g_inv

array([[s1, 0, 0, 0],
       [0, s1, 0, 0],
       [0, 0, s2, 0],
       [0, 0, 0, s2]], dtype=object)

In [10]:
x, mu, s = smp.symbols('x mu s', real=True)
pdf = 1/(s*smp.sqrt(2*np.pi))*smp.exp(-1/2*((x-mu)/s)**2)
pdf_times_x = pdf * x
pdf_times_x

0.398942280401433*x*exp(-0.5*(-mu + x)**2/s**2)/s

In [11]:
# Ensuring integrating normal distribution over real numbers is 1
smp.integrate(pdf, (x,-smp.oo,smp.oo))

Piecewise((0.564189583547756*sqrt(pi), Abs(arg(s)) <= pi/4), (Integral(0.398942280401433*exp(-0.5*(-mu + x)**2/s**2)/s, (x, -oo, oo)), True))

In [12]:
# Calculating Expected value of normal distribution
smp.integrate(pdf_times_x, (x,-smp.oo,smp.oo))

Piecewise((0.564189583547756*sqrt(pi)*mu, (Abs(arg(s)) <= pi/4) & (Abs(arg(s)) < pi/4)), (Integral(0.398942280401433*x*exp(-0.5*(-mu + x)**2/s**2)/s, (x, -oo, oo)), True))

In [15]:
x, y, mu1, mu2 = smp.symbols('x y mu1 mu2', real=True) # originally x, y, mu1,s1,mu2,s2 = smp.symbols('x y mu1 s1 mu2 s2', real=True)
s1, s2 = smp.symbols('s1 s2', real=True, positive = True)
# bivariate normal distribution
bi_pdf = 1/(s1*s2*np.sqrt(2*np.pi))*smp.exp(-1/2*(((x-mu1)/s1)**2+((y-mu2)/s2)**2))
bi_pdf

0.398942280401433*exp(-0.5*(-mu2 + y)**2/s2**2 - 0.5*(-mu1 + x)**2/s1**2)/(s1*s2)

In [11]:
# Calculating Expected value of bivariatte normal distribution
#smp.integrate(bi_pdf, (x,-smp.oo,smp.oo), (y, -smp.oo, smp.oo))
smp.integrate(bi_pdf, (x,-1,1), (y, -1, 1))

0.398942280401433*exp(-0.5*mu1**2/s1**2)*exp(-0.5*mu2**2/s2**2)*Integral(exp(-0.5*x**2/s1**2)*exp(1.0*mu1*x/s1**2), (x, -1, 1))*Integral(exp(-0.5*y**2/s2**2)*exp(1.0*mu2*y/s2**2), (y, -1, 1))/(s1*s2)

In [12]:
l_m = 1/s**2*(x-mu)
g_mm = smp.integrate(l_m**2*pdf, (x, -smp.oo,smp.oo))
g_mm

Piecewise((0.564189583547756*sqrt(pi)/s**2, Abs(arg(s)) < pi/4), (Integral(0.398942280401433*(-mu + x)**2*exp(-0.5*(-mu + x)**2/s**2)/s**5, (x, -oo, oo)), True))

0.564189583547756*sqrt(pi) = 1

In [13]:
l_s = (x-mu)**2/(2*s**4)-1/(2*s**2)
g_ss = smp.integrate(l_s**2*pdf, (x, -smp.oo,smp.oo))
g_ss

Piecewise((0.282094791773878*sqrt(pi)/s**4, (Abs(arg(s)) <= pi/4) & (Abs(arg(s)) < pi/4)), (Integral(0.398942280401433*(-1/(2*s**2) + (-mu + x)**2/(2*s**4))**2*exp(-0.5*(-mu + x)**2/s**2)/s, (x, -oo, oo)), True))

In [14]:
g_ms = smp.integrate(l_m*l_s*pdf, (x, -smp.oo,smp.oo))
g_sm = smp.integrate(l_s*l_m*pdf, (x, -smp.oo,smp.oo))
g_ms
g_sm

Piecewise((0, Abs(arg(s)) < pi/4), (Integral(0.398942280401433*(-mu + x)*(-1/(2*s**2) + (-mu + x)**2/(2*s**4))*exp(-0.5*(-mu + x)**2/s**2)/s**3, (x, -oo, oo)), True))

In [15]:
# Amari-Chentsov Tensor for C_mu_mu_mu
c_mmm = smp.integrate(l_m**3*pdf, (x, -smp.oo,smp.oo))
c_mmm

Piecewise((0, Abs(arg(s)) < pi/4), (Integral(0.398942280401433*(-mu + x)**3*exp(-0.5*(-mu + x)**2/s**2)/s**7, (x, -oo, oo)), True))

In [16]:
# Amari-Chentsov Tensor for C_s_mu_mu
c_smm = smp.integrate(l_s*l_m**2*pdf, (x, -smp.oo,smp.oo))
c_smm

Piecewise((0.564189583547756*sqrt(pi)/s**4, Abs(arg(s)) < pi/4), (Integral(0.398942280401433*(-mu + x)**2*(-1/(2*s**2) + (-mu + x)**2/(2*s**4))*exp(-0.5*(-mu + x)**2/s**2)/s**5, (x, -oo, oo)), True))

In [17]:
# Amari-Chentsov Tensor for C_s_s_mu
c_ssm = smp.integrate(l_s**2*l_m*pdf, (x, -smp.oo,smp.oo))
c_ssm

Piecewise((0, Abs(arg(s)) < pi/4), (Integral(0.398942280401433*(-mu + x)*(-1/(2*s**2) + (-mu + x)**2/(2*s**4))**2*exp(-0.5*(-mu + x)**2/s**2)/s**3, (x, -oo, oo)), True))

In [18]:
# Amari-Chentsov Tensor for C_s_s_s
c_sss = smp.integrate(l_s**3*pdf, (x, -smp.oo,smp.oo))
c_sss

Piecewise((0.564189583547756*sqrt(pi)/s**6, (Abs(arg(s)) <= pi/4) & (Abs(arg(s)) < pi/4)), (Integral(0.398942280401433*(-1/(2*s**2) + (-mu + x)**2/(2*s**4))**3*exp(-0.5*(-mu + x)**2/s**2)/s, (x, -oo, oo)), True))

In [19]:
# For bivariate normal distribution
l_mu1 = (x-mu2)/(s1**2)
l_mu2 = (y-mu2)/(s2**2)

l_s1 = (x-mu1)**2/(2*s1**4)-1/(2*s1**2)
l_s2 = (y-mu2)**2/(2*s2**4)-1/(2*s2**2)

In [20]:
# Amari-Chentsov Tensor for C_mu1_mu1_mu1
c_m1m1m1 = smp.integrate(l_mu1**3*bi_pdf, (x, 0,1), (y, 0, 1))
smp.simplify(l_mu1**3*bi_pdf)

-0.398942280401433*(mu2 - x)**3*exp(-0.5*(-mu2 + y)**2/s2**2 - 0.5*(-mu1 + x)**2/s1**2)/(s1**7*s2)

In [30]:
# maybe use fubini theorem
integrand_x = -1/(s1**7*s2*smp.sqrt(2*np.pi))*(mu2-x)**3*smp.exp(-1/2*((x-mu1)/s1)**2)
integrand_x
integral_x = smp.integrate(integrand_x, (x, -smp.oo,smp.oo))
integrand_x

-0.398942280401433*(mu2 - x)**3*exp(-0.5*(-mu1 + x)**2/s1**2)/(s1**7*s2)

In [29]:
integrand_y = smp.exp(-1/2*((y-mu2)/s2)**2)
integrand_y
integral_y = smp.integrate(integrand_y, (y, -smp.oo, smp.oo))
integrand_y

exp(-0.5*(-mu2 + y)**2/s2**2)

In [56]:
c_m1m1m1 = smp.integrate(l_mu1**3*bi_pdf, (x, -smp.oo,smp.oo), (y, -smp.oo, smp.oo))

KeyboardInterrupt: 

In [17]:
from sympy.stats import P, E, variance, Die, Normal
from sympy import simplify
X, Y = Normal('X', mu1, s1  ), Normal('Y', mu2, s2) # Define two six sided dice
P(X>3) # Probability X is greater than 3

sqrt(2)*s1*(-sqrt(2)*pi*(3 - mu1)*exp((3 - mu1)**2/(2*s1**2))*erf(sqrt(2)*(3 - mu1)/(2*s1))/(2*s1) + sqrt(2)*pi*(3 - mu1)*exp((3 - mu1)**2/(2*s1**2))/(2*s1))*exp((-mu1**2/2 + 3*mu1 - 9/2)/s1**2)/(2*pi*(3 - mu1))

In [18]:
E(X+Y) # Expectation of the sum of normal distributions

mu1 + mu2

In [19]:
E(X**2)

mu1**2 + s1**2

In [20]:
E(X**3)

mu1**3 + 3*mu1*s1**2

In [21]:
E(X*Y)

mu1*mu2

In [78]:
# April 4th, 2023
# Redefine all variables and derivatives

l_mu1 = (X-mu1)/(s1**2) # might have to change x to X for normal distribution
l_mu2 = (Y-mu2)/(s2**2)
l_s1 = (X-mu1)**2/(2*s1**4)-1/(2*s1**2)
l_s2 = (Y-mu2)**2/(2*s2**4)-1/(2*s2**2)

# derivative w.r.t. sigma^2
l_s1_sq = (X-mu1)**2/s1**3 - s1**(-1)
l_s2_sq = (Y-mu2)**2/s2**3 - s2**(-1)

derv = [l_mu1, l_s1, l_mu2, l_s2] # derivatives w.r.t t1,...,t4
derv[1]
# with squared derivatives
derv_sq = [l_mu1, l_s1_sq, l_mu2, l_s2_sq]

In [79]:
l_s1_sq

-1/s1 + (-mu1 + X)**2/s1**3

In [80]:
# Amari-Chentsov Tensor Matrix
l_mu1_X = (X-mu1)/(s1**2)

# check to see T_111 is equal to 0; it is
E(l_mu1_X**3)
smp.simplify(E(l_mu1_X**3))

smp_dtype = type(E(l_mu1_X**3))

In [81]:
# step 4
T = np.zeros((4,4,4), dtype = smp_dtype)
for i in range(4):
    for j in range(4):
        for k in range(4):
            T[i][j][k] = smp.simplify(E(derv_sq[i]*derv_sq[j]*derv_sq[k]))

In [82]:
T

array([[[0, 2/s1**3, 0, 0],
        [2/s1**3, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[2/s1**3, 0, 0, 0],
        [0, 8/s1**3, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 2/s2**3],
        [0, 0, 2/s2**3, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 2/s2**3, 0],
        [0, 0, 0, 8/s2**3]]], dtype=object)

In [40]:
smp.simplify(E(l_s1**3))

s1**(-6)

In [83]:
# step 5
# Assunming Cubic Tensor is correct, will now create alpha-christoffel symbol

def alpha_chrst(a):
    a_chrst = np.zeros((4,4,4), dtype = smp_dtype)
    for i in range(4):
        for j in range(4):
            for k in range(4):
                a_chrst[i][j][k] = H2_chrst[i][j][k] + (a/2)*T[i][j][k]
    return a_chrst

In [84]:
zero_alpha = alpha_chrst(0)

In [85]:
zero_alpha

array([[[0, 0.5/s1, 0, 0],
        [-0.5/s1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[-0.5/s1, 0, 0, 0],
        [0, -0.5/s1, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0.5/s2],
        [0, 0, -0.5/s2, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, -0.5/s2, 0],
        [0, 0, 0, -0.5/s2]]], dtype=object)

In [72]:
sum1 = 0
sum2 = 0
for p in range(4):
    sum1 += (zero_alpha[0][1][p]*zero_alpha[1][p][0])
    sum2 += (zero_alpha[1][1][p]*zero_alpha[0][p][0])
sum1-sum2
    
    

-0.5/s1**2

In [88]:
sum1 = 0
sum2 = 0
sum3 = 0
sum4 = 0

for p in range(4):
    sum1 += zero_alpha[0][1][p]
    sum2 += zero_alpha[1][p][0]
    sum3 += zero_alpha[1][1][p]
    sum4 += zero_alpha[0][p][0]


print(sum1)
print(sum2)
print(sum3)
print(sum4)
#print(sum1*sum2)
#print(sum3*sum4)

-0.5/s1
-0.5/s1
-0.5/s1
-0.5/s1


In [54]:
print(alpha_chrst(1))

[[[0 -0.5/s1 + 1.0/s1**3 0 0]
  [-0.5/s1 + 1.0/s1**3 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0.5/s1 + 1.0/s1**3 0 0 0]
  [0 -0.5/s1 + 4.0/s1**3 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 -0.5/s2 + 1.0/s2**3]
  [0 0 -0.5/s2 + 1.0/s2**3 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0.5/s2 + 1.0/s2**3 0]
  [0 0 0 -0.5/s2 + 4.0/s2**3]]]


In [86]:
# step 6
R = np.zeros((4,4,4,4), dtype = smp_dtype)
partials = [mu1, s1, mu2, s2]

def alpha_tensor(a):
    ac = alpha_chrst(a) # alpha christoffel symbol
    R = np.zeros((4,4,4,4), dtype = smp_dtype)
    for i in range(4):
        for j in range(4):
            for k in range(4):
                for l in range(4):
                    chrst_ikp = 0
                    chrst_jpl = 0
                    chrst_jkp = 0
                    chrst_ipl = 0
                    for p in range(4):
                        chrst_ikp += ac[i][k][p]
                        chrst_jpl += ac[j][p][l]
                        chrst_jkp += ac[j][k][p]
                        chrst_ipl += ac[i][p][l]
                    
                    # now plug in to formula
                    
                    R[i][j][k][l] = smp.diff(ac[i][k][l],partials[j]) - smp.diff(ac[j][k][l], partials[i]) + \
                    (chrst_ikp*chrst_jpl - chrst_jkp*chrst_ipl)
                    
                    
    return R

In [89]:
alpha_tensor(0)[0][2][0][2]

-0.25/(s1*s2)

In [90]:
# step 6 (test) not how you're supposed to do einstein notation
R = np.zeros((4,4,4,4), dtype = smp_dtype)
partials = [mu1, s1, mu2, s2]

def test_alpha_tensor(a):
    ac = alpha_chrst(a) # alpha christoffel symbol
    R = np.zeros((4,4,4,4), dtype = smp_dtype)
    for i in range(4):
        for j in range(4):
            for k in range(4):
                for l in range(4):
                    sum1 = 0
                    sum2 = 0
                    for p in range(4):
                        sum1 += ac[i][k][p]*ac[j][p][l]
                        sum2 += ac[j][k][p]*ac[i][p][l]
                    
                    # now plug in to formula
                    
                    R[i][j][k][l] = smp.diff(ac[i][k][l],partials[j]) - smp.diff(ac[j][k][l], partials[i]) + \
                    (sum1 - sum2)
                    
    return R

In [91]:
test_alpha_tensor(0)

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, -0.5/s1**2, 0, 0],
         [0.5/s1**2, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0.5/s1**2, 0, 0],
         [-0.5/s1**2, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],

In [96]:
# step 7: calculate alpha_R_ijkl
g = np.zeros((4,4), dtype = smp_dtype) # for H2xH2
g[0][0] = 1/s1
g[1][1] = 1/s1
g[2][2] = 1/s2
g[3][3] = 1/s2

def sum_R_ijkl(a):
    R = np.zeros((4,4,4,4), dtype = smp_dtype)
    tensor = alpha_tensor(a)
    for i in range(4):
        for j in range(4):
            for k in range(4):
                for l in range(4):
                    for s in range(4):
                        R[i][j][k][l] += tensor[i][j][k][s]*g[l][s]
    return R

In [97]:
sum_R_ijkl(0)

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[-0.5/s1**3, -0.5/s1**3, 0, 0],
         [0.5/s1**3, 0.5/s1**3, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, -0.25/(s1*s2**2), 0.25/(s1*s2**2)],
         [0, 0, 0.25/(s1*s2**2), -0.25/(s1*s2**2)],
         [0.25/(s1**2*s2), -0.25/(s1**2*s2), 0, 0],
         [-0.25/(s1**2*s2), 0.25/(s1**2*s2), 0, 0]],

        [[0, 0, -0.25/(s1*s2**2), -0.25/(s1*s2**2)],
         [0, 0, 0.25/(s1*s2**2), 0.25/(s1*s2**2)],
         [-0.25/(s1**2*s2), 0.25/(s1**2*s2), 0, 0],
         [-0.25/(s1**2*s2), 0.25/(s1**2*s2), 0, 0]]],


       [[[0.5/s1**3, 0.5/s1**3, 0, 0],
         [-0.5/s1**3, -0.5/s1**3, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0.25/(s1*s2**2), -0.25/(s1*s2**2)],
         [0, 0, 0.25/(s1*s2**2), -0.25/(s1*s2**2)],
         [0.25/(s1**2*s2), 0.2

In [100]:
# step 8: calculating sectional curvature (numerator)
u1, u2, u3, u4 = smp.symbols('u1 u2 u3 u4', real=True)
v1, v2, v3, v4 = smp.symbols('v1 v2 v3 v4', real=True)
#u = [u1,u2,u3,u4]
#v = [v1,v2,v3,v4]
u = [1,4,1,6]
v = [-1,2,3,-7]

# inner product function
def dot(u,v):
    return np.dot(u,v)

# calculating numerator since denominator always positive
def calculate_sectional_curvature(a):
    R = sum_R_ijkl(a)
    numerator = 0
    denominator = dot(u,u)*dot(v,v)-(dot(u,v)**2)
    for i in range(4):
        for j in range(4):
            for k in range(4):
                for l in range(4):
                    numerator += v[j]*u[i]*R[i][j][k][l]*u[l]*v[k]
    
    sectional_curvature = smp.simplify(numerator) / denominator
    #return sectional_curvature
    return smp.simplify(numerator)

In [101]:
calculate_sectional_curvature(0)

71289.0/s2**3 - 13104301.75/(s1*s2**2) - 55077.0/(s1**2*s2) + 20470.0/s1**3

In [344]:
s1 > 0

True

# For S2XS2

In [245]:
tha1, phi1, tha2, phi2 = smp.symbols('tha1 phi1 tha2 phi2', real=True)
G = np.zeros((4,4), dtype = smp_dtype)
G[0][0] = 1
G[1][1] = smp.sin(tha1)**2
G[2][2] = 1
G[3][3] = smp.sin(tha2)**2

G_inv = np.zeros((4,4), dtype = smp_dtype)
G_inv[0][0] = 1
G_inv[1][1] = 1/(smp.sin(tha1)**2)
G_inv[2][2] = 1
G_inv[3][3] = 1/(smp.sin(tha2)**2)

In [300]:
# calculating christoffel symbols

var = [tha1, phi1, tha2, phi2]

def calc_s2_chrst():
    s2_chrst = np.zeros((4,4,4), dtype = smp_dtype)
    for k in range(4):
        for i in range(4): 
            for j in range(4):
                for m in range(4):
                    s2_chrst[k][i][j] += (1/2)*G_inv[k][m]*(smp.diff(G[m][i],var[j]) + smp.diff(G[m][j],var[i]) - smp.diff(G[i][j],var[m]))
                s2_chrst[k][i][j] = smp.simplify(s2_chrst[k][i][j])
    return s2_chrst

print(calc_s2_chrst())

[[[0 0 0 0]
  [0 -0.5*sin(2*tha1) 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 1.0/tan(tha1) 0 0]
  [1.0/tan(tha1) 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 -0.5*sin(2*tha2)]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 1.0/tan(tha2)]
  [0 0 1.0/tan(tha2) 0]]]


In [301]:
s2_chrst = calc_s2_chrst()

In [302]:
s2_chrst[3][3][2] # checked all christoffel symbols and all match paper

1.0/tan(tha2)

In [303]:
# Second step : computing the components of the curvature R

def compute_s2_curvature_R():
    R = np.zeros((4,4,4,4), dtype = smp_dtype)
    for i in range(4):
        for j in range(4):
            for k in range(4):
                for s in range(4):
                    sum1 = 0
                    sum2 = 0
                    for l in range(4):
                        sum1 += s2_chrst[i][k][l]*s2_chrst[l][j][s]
                        sum2 += s2_chrst[j][k][l]*s2_chrst[i][k][s]
                    
                    R[i][j][k][s] = smp.diff(s2_chrst[i][k][s], var[j]) - smp.diff(s2_chrst[j][k][s], var[i]) \
                                    + sum1 - sum2
                    R[i][j][k][s] = smp.simplify(R[i][j][k][s])
    return R

In [304]:
compute_s2_curvature_R()

array([[[[0, 0, 0, 0],
         [0, -0.5*sin(2*tha1)/tan(tha1) + 0.125*cos(4*tha1) - 0.125, 0,
          0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 1.0/sin(tha1)**2, 0, 0],
         [-0.5*sin(2*tha1)/tan(tha1) - 2.0/(cos(2*tha1) - 1),
          0.5*sin(2*tha1)/tan(tha1), 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, -1.00000000000000, 0, 0],
         [1.0*cos(tha1)**2 - 1.0/sin(tha1)**2, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1.0/tan(tha1)**2, -1.0/tan(tha1)**2, 0, 0],
         [-1.0/tan(tha1)**2, -0.5*sin(2*tha1)/tan(tha1), 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0